version: '3.1'
services:
  simpleweb:
    build:
      context: ./
      dockerfile: Dockerfile.local
    restart: always
    depends_on:
      - db
    environment:
      db_name: test
      db_username: postgres
      db_password: IIIdevops123!
      db_host: db
    ports:
      - 8080
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: IIIdevops123!
    volumes:
      - ./db:/docker-entrypoint-initdb.d:rw
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080
